#!/usr/bin/env sh

if [ -z "$1" ] || ! [ -s "$1" ]; then
    printf "empty file"
    read -r _
    exit 1
fi

if command -v sxiv >/dev/null 2>&1; then
    if [ -f "$1" ]; then
        sxiv -qa "$PWD" & disown
    elif [ -d "$1" ] || [ -h "$1" ]; then
        sxiv -qat "$1" & disown
    fi
else
    exit 1
fi
