notify = true
volnorm = true
volnorm_pregain = -3

[saved_state]
volume = 82
repeat = "playlist"
shuffle = false

[theme]
primary = "white"
secondary = "#B080FF"
title = "green"
playing = "green"
playing_selected = "black"
#playing_bg = "#b0b0ff"
highlight = "black"
highlight_bg = "#B080FF"
error = "white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "green"
statusbar_bg = "#B080FF"
cmdline = "green"
cmdline_bg = "black"
