notify = false
volnorm = true
volnorm_pregain = -3

[saved_state]
volume = 100
repeat = "playlist"
shuffle = true

[keybindings]
"Shift+r" = "reload"

# MC THEME
#[theme]
#background = "#0000ff"
#primary = "#ffffff"
#secondary = "#ffffff"
#title = "#ffff00"
#playing = "#ffff00"
#playing_bg = "#0000ff"
#playing_selected = "#000000"
#highlight = "#000000"
#highlight_bg = "#00ffff"
#statusbar = "#000000"
#statusbar_bg = "#ffffff"
#statusbar_progress = "#ffffff"
